apiVersion: v1
kind: Secret
metadata:
    name: cms-directus-config
stringData:
    config.yaml: ENC[AES256_GCM,data:B1qJztDtfLq3CZ2/g3lJvEAesrEo+R342D/AQpWahn9mrRpoOl+S3Mg3t/QsWaAE7m4c08x1q/GuZvb+aMNQV1CR/HcyMD6BM2kaiev6Wv5VRNr8CGHjTylP1nu0CMKmbHHXRHP/9b1Mq1GrkqTUeYjnPR9f1CxS0Epav8o+HnryS6rl9v/81TdViIDq4DXCXWToldUdcMpEZXrS/tus3E00bPPjI4bLhFsNKNGzlDhH3ynMK58=,iv:7FU7S65JSo/vrLaYsneChQCKZ91OmJrBvxtOgsfEKTY=,tag:32t/CUpa2EQPKV7a5Nb28Q==,type:str]
sops:
    age:
        - recipient: age1xelh7mcaqflyydn3nxem553pt3tlqkqhyacsmuqefl0xs6vk938sy378gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhQmpYNlQ4VmVrWlJWL1Vt
            SkNLYkU2Ry9IeG5ZWUJyNTZLVHlzL1gzWUhrCjF5TGdOQUEyTGI3Qytuc2duZkty
            VmpqaEt6RSszNW1KSFFxRHVobmZXbHcKLS0tIHFxSFJtbDJCY3VzMjA0emhPb3VV
            RXpacXB2OGZSM2EvalhYaklOanBQdDQKXi2JPdNEBu8Hm759epQck5jvlUXyyclM
            Xw+BCJ4ba82UwakGWq+PbQKGXdFBNzkatzaHYvlJG9YGU8skTomucg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T20:37:30Z"
    mac: ENC[AES256_GCM,data:vZz2fR0AmsbmuHRhYOy7bKmWDpW0xUrm1dAYRqE58sYlXYtC3BxKJRdeKgGrfv461IgCqnvaIj0ifkgzViWs2PTlGc+btA/OQjTgcF47z1fP5h+oC0BGEEAf0p3AigV5vFDbcdocgjPB26IOn5+UkjVEcEjU5wNEgARhcsWXkTQ=,iv:BViWxRLG9OYx8ukir7sv5vOcCwHcxUkCaVZj0y6hb64=,tag:beyo82ZC2xda8uHiI0SvBw==,type:str]
    encrypted_regex: ^(config.yaml|)$
    version: 3.10.2
