apiVersion: v1
kind: Secret
metadata:
    name: cms-directus-config
stringData:
    config.yaml: ENC[AES256_GCM,data:aHG3zMj3S8omCWxkShY5yRsVHvoBvozuzwl7hhdN5YBFQTuritq52MdDsUMFYNTk5IvfRJAFOOwIJIdrpFbxMaTG7wwRwGvptOYDsA0n7YLjZ404mHhqMl9tHyKT/VZpHRR100jTaGbMip6diH4wAoqqP6VuNKIqYZ2/Ifei96r8C7BoTeY7ddYvcSxI3yUKtaGM0YrHb4Q3kmn7V3jYEblBvFwUvs5obuMmup3W786jQVk9mU3FlxecdIw=,iv:Doc3u+2OhLIkZfUaBpgM6UpTQ4yaKtgP/vkVUno0r+g=,tag:IRV7MtZW8+9T6BZqYkwrQA==,type:str]
sops:
    age:
        - recipient: age1xelh7mcaqflyydn3nxem553pt3tlqkqhyacsmuqefl0xs6vk938sy378gm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpR0x5cHoxTkVadEM4K2dZ
            cXpOQS9aME8xQTJLQ3MwL1QxUE1vMmZaR0IwCm9aS3lScWk5OXNpK2g0NTBjVE5p
            RHVWL0hSdDlTemx0dWovQ2JnTnA3Y2cKLS0tIGtlOUxVL2NBbVhNdU9ZNllrR1M1
            Z2NZWDczMmJVQXZxR1NHQk9SYmE4T3cKaT+TvAGyvW60wnntCoGa0epRBivF7y6Z
            sQ9UIPCy7o439nPXahcw0Y0qDuNGA/MLzFtqlaV8Ij7TI4GLv8H6SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T20:24:08Z"
    mac: ENC[AES256_GCM,data:ulIPKaZXSY8hnlU8RNgeh3OMjbSbN73lyRtH8lsm1s72yExFY++6mWNzbYuLiBM+Q4f5it8EdgjkRmSlC9w5KrCimgv7wA3cAaDEaYdu98dOdso7E+FbrV7sSk6ZDWZuIgQA7Dtsvs7Vy4nIuX8/ZAwNGQeSuWGXsGy1W0jCRgg=,iv:BdgIOQaE3pxHoEYWPQWH842X1wEhmDi1DbCmHk1n+wU=,tag:A1K6XEN49w+ZRurtHNGWgA==,type:str]
    encrypted_regex: ^(config.yaml|)$
    version: 3.10.2
